In [2]:
import torch


torch._logging.set_logs(graph_code=True)

In [3]:
def foo(x, y):
    a = torch.sin(x)
    b = torch.cos(y)
    return a + b


opt_foo1 = torch.compile(foo)
print(opt_foo1(torch.randn(3, 3), torch.randn(3, 3)))


@torch.compile
def opt_foo2(x, y):
    a = torch.sin(x)
    b = torch.cos(y)
    return a + b


print(opt_foo2(torch.randn(3, 3), torch.randn(3, 3)))

V1110 19:55:34.814000 22813 torch/_dynamo/output_graph.py:1983] [0/0] [__graph_code] TRACED GRAPH
V1110 19:55:34.814000 22813 torch/_dynamo/output_graph.py:1983] [0/0] [__graph_code]  ===== __compiled_fn_1_98bfb258_f1f8_4138_953c_7fe6f2b01a2e =====
V1110 19:55:34.814000 22813 torch/_dynamo/output_graph.py:1983] [0/0] [__graph_code]  /Users/Deependu/notes/red-arrow/.venv/lib/python3.12/site-packages/torch/fx/_lazy_graph_module.py class GraphModule(torch.nn.Module):
V1110 19:55:34.814000 22813 torch/_dynamo/output_graph.py:1983] [0/0] [__graph_code]     def forward(self, L_x_: "f32[3, 3][3, 1]cpu", L_y_: "f32[3, 3][3, 1]cpu"):
V1110 19:55:34.814000 22813 torch/_dynamo/output_graph.py:1983] [0/0] [__graph_code]         l_x_ = L_x_
V1110 19:55:34.814000 22813 torch/_dynamo/output_graph.py:1983] [0/0] [__graph_code]         l_y_ = L_y_
V1110 19:55:34.814000 22813 torch/_dynamo/output_graph.py:1983] [0/0] [__graph_code]         
V1110 19:55:34.814000 22813 torch/_dynamo/output_graph.py:1983]

tensor([[ 1.3670e-01,  1.7276e+00, -3.7221e-01],
        [-1.3269e-03, -1.0509e+00, -2.0892e-02],
        [ 1.4534e+00,  8.0737e-01,  7.5619e-01]])
tensor([[-0.7475, -0.0232, -1.8530],
        [ 1.9620,  1.1253,  1.5489],
        [ 1.5670,  0.1449, -0.0686]])


In [4]:
def inner(x):
    return torch.sin(x)


@torch.compile
def outer(x, y):
    a = inner(x)
    b = torch.cos(y)
    return a + b


print(outer(torch.randn(3, 3), torch.randn(3, 3)))

V1110 19:57:45.459000 22813 torch/_dynamo/output_graph.py:1983] [2/0] [__graph_code] TRACED GRAPH
V1110 19:57:45.459000 22813 torch/_dynamo/output_graph.py:1983] [2/0] [__graph_code]  ===== __compiled_fn_5_920067cf_9c67_454c_b5fb_96677de8051f =====
V1110 19:57:45.459000 22813 torch/_dynamo/output_graph.py:1983] [2/0] [__graph_code]  /Users/Deependu/notes/red-arrow/.venv/lib/python3.12/site-packages/torch/fx/_lazy_graph_module.py class GraphModule(torch.nn.Module):
V1110 19:57:45.459000 22813 torch/_dynamo/output_graph.py:1983] [2/0] [__graph_code]     def forward(self, L_x_: "f32[3, 3][3, 1]cpu", L_y_: "f32[3, 3][3, 1]cpu"):
V1110 19:57:45.459000 22813 torch/_dynamo/output_graph.py:1983] [2/0] [__graph_code]         l_x_ = L_x_
V1110 19:57:45.459000 22813 torch/_dynamo/output_graph.py:1983] [2/0] [__graph_code]         l_y_ = L_y_
V1110 19:57:45.459000 22813 torch/_dynamo/output_graph.py:1983] [2/0] [__graph_code]         
V1110 19:57:45.459000 22813 torch/_dynamo/output_graph.py:1983]

tensor([[ 1.1975,  1.4264,  0.5204],
        [ 1.1221, -0.9894,  1.2334],
        [ 0.5513,  1.3970,  1.1348]])


In [5]:
class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.lin = torch.nn.Linear(3, 3)

    def forward(self, x):
        return torch.nn.functional.relu(self.lin(x))


mod1 = MyModule()
mod1.compile()
print(mod1(torch.randn(3, 3)))

mod2 = MyModule()
mod2 = torch.compile(mod2)
print(mod2(torch.randn(3, 3)))

V1110 19:59:08.770000 22813 torch/_dynamo/output_graph.py:1983] [3/0] [__graph_code] TRACED GRAPH
V1110 19:59:08.770000 22813 torch/_dynamo/output_graph.py:1983] [3/0] [__graph_code]  ===== __compiled_fn_7_fa869ad0_7769_4148_a003_061f53e18e7e =====
V1110 19:59:08.770000 22813 torch/_dynamo/output_graph.py:1983] [3/0] [__graph_code]  /Users/Deependu/notes/red-arrow/.venv/lib/python3.12/site-packages/torch/fx/_lazy_graph_module.py class GraphModule(torch.nn.Module):
V1110 19:59:08.770000 22813 torch/_dynamo/output_graph.py:1983] [3/0] [__graph_code]     def forward(self, L_self_modules_lin_parameters_weight_: "f32[3, 3][3, 1]cpu", L_self_modules_lin_parameters_bias_: "f32[3][1]cpu", L_x_: "f32[3, 3][3, 1]cpu"):
V1110 19:59:08.770000 22813 torch/_dynamo/output_graph.py:1983] [3/0] [__graph_code]         l_self_modules_lin_parameters_weight_ = L_self_modules_lin_parameters_weight_
V1110 19:59:08.770000 22813 torch/_dynamo/output_graph.py:1983] [3/0] [__graph_code]         l_self_modules_li

tensor([[0.0000, 0.6000, 0.3552],
        [1.0293, 0.2921, 0.0000],
        [0.3256, 0.0052, 0.0000]], grad_fn=<CompiledFunctionBackward>)
tensor([[0.4790, 0.7246, 0.0000],
        [1.5001, 0.2692, 0.0000],
        [0.5898, 0.4999, 0.0000]], grad_fn=<CompiledFunctionBackward>)


In [6]:
def foo3(x):
    y = x + 1
    z = torch.nn.functional.relu(y)
    u = z * 2
    return u


opt_foo3 = torch.compile(foo3)


# Returns the result of running `fn()` and the time it took for `fn()` to run,
# in seconds. We use CUDA events and synchronization for the most accurate
# measurements.
def timed(fn):
    start = torch.cuda.Event(enable_timing=True)
    end = torch.cuda.Event(enable_timing=True)
    start.record()
    result = fn()
    end.record()
    torch.cuda.synchronize()
    return result, start.elapsed_time(end) / 1024


inp = torch.randn(4096, 4096).cuda()
print("compile:", timed(lambda: opt_foo3(inp))[1])
print("eager:", timed(lambda: foo3(inp))[1])

AssertionError: Torch not compiled with CUDA enabled